# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d08d915a771e5a97eaf4a88481a9506c37b7f8452fc2309e3c246e21778ad1a854363b14ef70c9008027322a59d6fb0beb1b5bece196e93d29a766e591628576

test:
  secret_key_base: 17c0bd0ba308d29ff4454667aa0c6d2e3c9a684f7b3e7274e7832fc11a17046882d181a3e8be7ed37d4c401493d02536cb4aad5fd2403b1b9f9cbbd9c061136b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
